### ISSUE TITLE
FS_reconstruction submit print several times

### ISSUE THREAD

**Issue by MadsJensen** [cfin-tools/stormdb#13]
When using the submit_to_cluster several the submission is printed several times, but only is only submitted once.

**Comment by cjayb** [comment]
Hmm, not sure I understand, what's the output? Actually, is this `Maxfilter.submit_to_cluster()` or `stormdb.process.submit_to_cluster()`? Nice naming... ;)

**Comment by cjayb** [comment]
Closing due to #32
