### ISSUE TITLE
freesurfer recon-all stalls at dicom conversion

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/stormdb#33]
The `-i` flag to `recon-all` seems to be _extremely_ slow on hyades. The culprit is `mri_info`, which reads the DICOM headers.

This seems to be a bug or incompatibility of `Freesurfer` with the hyades file system. To circumvent it, I will modify `Freesurfer.recon_all`to make a copy of the DICOM folder before conversion, then delete it.

NB @MadsJensen

**Comment by ahoejlund** [comment]
Nice catch, Chris!

**Comment by cjayb** [comment]
I may have to re-think my approach, I don't like the idea of copying at all, let alone the mess it will make in the code. Another (feeble) hope is that FS 6.0 will work better, downloading the beta-version now...
