### ISSUE TITLE
highmem queue memory limit logic needs fixing

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/stormdb#53]
TL;DR all qsub jobs on hyades have an 8 GB soft limit per slot by default. highmem.q has x2 hardlimit (16 GB) compared with all other queues. To actually use the full 16 GB capacity, the qsub command needs to be modified as per below.

Jeg har fået bekræftet, at der er en 8 GB grænse per job, også på highmem køen. Dette skyldes, at jeg har konfigureret at der er en standard grænse på 8 GB per slot, når man submitter et job.

Derudover er der hardlimit på hukommelsen, som er 8 GB/slot for all og short køen, men denne grænse er 16 GB/slot for highmem. Men default værdien ved qsub er stadig 8 GB/slot. Men det kan du selv angive (hardlimit kan der dog ikke ændres ved).

Hvis du skriver:

```
qsub -q highmem.q -l h_vmem=16G job.sh
```

så vil dette job kunne bruge 16 GB (på een CPU/slot). Skriver du i stedet:

```
qsub -pe threaded 2-2 -q highmem.q -l h_vmem=16G job.sh
```

så kan jobbet bruge (max) 32 GB RAM, på 2 CPU/slots

**Comment by MadsJensen** [comment]
Det virker hvis du du giver "-m" som parameter og beder om mere RAM end et slot har. Hvis du bare siger du vil have to slots får du stadig kun 8Gb per slot på highmem.

**Comment by cjayb** [comment]
Nåjah, det er jo smart nok at man kan sige -n 6 på highmem (uden -m) og så få 16 GB per thread. Skulle virke sådan nu, vil du teste?

**Comment by MadsJensen** [comment]
Det manglede "opt_mem_free_flag".

**Comment by cjayb** [comment]
fjernede det helt, virker til at køre nu, +1 for merge?
