### ISSUE TITLE
multifile (>2GB) fif files ordered wrongly in 'files'

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/stormdb#69]
When using `filter_series`, the series with multi-file acquisitions have the first acquisition (without suffix) last.

Same applies to `get_files`

Order is inherited from filesystem

**Comment by cjayb** [comment]
For example, here last item should be first:

```python
In [34]: qy.get_files('0007','20190128_000000','MEG',1)
Out[34]:
['/projects/MINDLAB2018_MEG-SF-Integration-Images/raw/0007/20190128_000000/MEG/001.0007_RVB_SFtuned/files/0007_RVB_SFtuned-1.fif',
 '/projects/MINDLAB2018_MEG-SF-Integration-Images/raw/0007/20190128_000000/MEG/001.0007_RVB_SFtuned/files/0007_RVB_SFtuned-2.fif',
 '/projects/MINDLAB2018_MEG-SF-Integration-Images/raw/0007/20190128_000000/MEG/001.0007_RVB_SFtuned/files/0007_RVB_SFtuned-3.fif',
 '/projects/MINDLAB2018_MEG-SF-Integration-Images/raw/0007/20190128_000000/MEG/001.0007_RVB_SFtuned/files/0007_RVB_SFtuned-4.fif',
 '/projects/MINDLAB2018_MEG-SF-Integration-Images/raw/0007/20190128_000000/MEG/001.0007_RVB_SFtuned/files/0007_RVB_SFtuned.fif']
```

**Comment by cjayb** [comment]
Totally weird thing is `sort` or `sorted` don't work!

This is as expected:
```python
In [42]: sorted(['ab','ac','a'])
Out[42]: ['a', 'ab', 'ac']
```

As is this:

```python
In [43]: sorted(['a-1','a-2','a'])
Out[43]: ['a', 'a-1', 'a-2']
```

**But this doesn't work, why?!?**
```python
In [44]: sorted(['a-1.fif','a-2.fif','a.fif'])
Out[44]: ['a-1.fif', 'a-2.fif', 'a.fif']
```

And this indicates that the hyphen is somehow to blame:

```python
In [45]: sorted(['a1.fif','a2.fif','a.fif'])
Out[45]: ['a.fif', 'a1.fif', 'a2.fif']
```

And then, this:

```python
In [49]: sorted(['a-1.fif','a-2.fif','a.fif'], key=lambda x:x[:-4])
Out[49]: ['a.fif', 'a-1.fif', 'a-2.fif']
```

**WTF?????** @MadsJensen @britta-wstnr @Lubell

[credits to SO](https://stackoverflow.com/questions/2289870/sort-lines-in-text-file-but-only-use-the-first-n-characters#2289911)

**Comment by Lubell** [comment]
It has to do with the number of elements in each item of the list being sorted.
From the sorted documentation:
>  A sort is stable if it guarantees not to change the relative order of elements that compare equal — this is helpful for sorting in multiple passes (for example, sort by department, then by salary grade).

If you try this it works, note the white space between 'a' and the '.':
`In [6]: sorted(['a-1.ff', 'a-2.ff', 'a .ff'])  
Out[7]: ['a .ff', 'a-1.ff', 'a-2.ff']`


@cjayb @britta-wstnr @MadsJensen

**Comment by cjayb** [comment]
Well, kinda, but I figure it out this morning:

```python
In [5]: sorted(['-', '.', ' '])
Out[5]: [' ', '-', '.']
```

_i.e._, the hyphen '-' sorts before the period '.' Therefore, 

```python
In [6]: sorted(['foo.bar', 'foo-whatever.bar'])
Out[6]: ['foo-whatever.bar', 'foo.bar']
```

**Comment by cjayb** [comment]
Two possible solutions

1. First sort alphabetically, then on string length (the "stability" of `sort` would make this work).
2. Sort without extension (inspired by [this SO page](https://stackoverflow.com/questions/30003624/python-sort-on-extension-name-of-the-file/30003951#30003951) and [the docs](https://docs.python.org/3/howto/sorting.html)):

```python
from os.path import splitext
sorted(['fname-2.fif', 'fname.fif', 'fname-1.fif'], key=lambda x: splitext(x)[0])
```

My money's on 2. Will work on FIF and DCM files. Generally it would also work on files with multiple periods in the file name. I can't think of when 1. might fail, but somehow it seems 'wronger'...

Can I get a vote, @Lubell @MadsJensen @britta-wstnr

**Comment by ahoejlund** [comment]
My vote’s on 2, as well. 
2 seems like a more “common” approach to me than 1 - I’d be worried there’d be scenarios where it’d break/mock up even tho I can’t necessarily think of one right now...

**Comment by Lubell** [comment]
Just messing around and both sorted (alpha then length sort) and splitext have a problem with this case:
```
In [3]: from os.path import splitext 
   ...: sorted(['fname-2.fif', 'fname..fif', 'fname-1.fif'], key=lambda x: splitext(x)[0])                                                 
Out[3]: ['fname-1.fif', 'fname-2.fif', 'fname..fif']
```
sorted is no better in the same circumstances:
```
 In [4]: sorted(['fname-2.fif', 'fname..fif', 'fname-1.fif'])                                                                                
Out[4]: ['fname-1.fif', 'fname-2.fif', 'fname..fif']
```
In a perfect world I'd go with option 1 though.
@MadsJensen @britta-wstnr @cjayb

**Comment by cjayb** [comment]
Have to be careful no to overthink this, though @Lubell I acknowledge that your example is a perfectly feasible situation when doing manual file naming (near-future EEG uploads, 2-photon, etc.). MEG files will never have more than one period (unless of course someone alters names directly on the file system!)

Unless I get more votes for 1., I'm going to merge later today as-is (#70 is with 2.). I only realised this bug now that I was helping someone with an MF-run. For DICOM it wouldn't even matter, since `dcm2X`-converters read the header info and order slices according to those.
