### ISSUE TITLE
[BUG] Query returns values regardless of group membership

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/stormdb#71]
Users probably shouldn't be allowed to make `Query`s into projects they don't have read access in...

Remedy might be as simple as testing for file system access.

**Comment by cjayb** [comment]
@Lubell I just realised I may have special powers as a member of the admin group. Could you get the latest git master and test this code:

```python
from stormdb.access import Query
qy = Query('MEG_Headmodel')
qy.get_subjects()
```

Do you get output?

**Comment by Lubell** [comment]
Didn't even get to the qy.get_subjects() output.

Python 3.7.1 (default, Dec 14 2018, 19:28:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from stormdb.access import Query

In [2]: qy = Query('MEG_Headmodel')
Login credentials not found, please enter them here
WARNING: This might not work if you're in an IDE (e.g. spyder)!
User "lubell", please enter your password:
Code generated, writing to ~/.stormdblogin
---------------------------------------------------------------------------
DBError                                   Traceback (most recent call last)
<ipython-input-2-66d4058eca62> in <module>
----> 1 qy = Query('MEG_Headmodel')

~/Documents/stormdb-python-master/stormdb/access.py in __init__(self, proj_name, stormdblogin, verbose)
    101
    102         self._get_login_code()
--> 103         self._check_login_credentials()  # checks templogin and proj_name
    104
    105     def _get_login_code(self):

~/Documents/stormdb-python-master/stormdb/access.py in _check_login_credentials(self)
    171         url = ('testlogin?{login:s}&projectCode={proj:s}'
    172                ''.format(login=self._login_code, proj=self.proj_name))
--> 173         self._send_request(url)
    174
    175     def _send_request(self, url, verbose=None):

~/Documents/stormdb-python-master/stormdb/access.py in _send_request(self, url, verbose)
    206                 print(full_url)
    207                 print(38 * '*')
--> 208             raise e
    209
    210         # Python 3.x treats pipe strings as bytes, which need to be encoded

~/Documents/stormdb-python-master/stormdb/access.py in _send_request(self, url, verbose)
    200
    201         try:
--> 202             self._check_response(response)
    203         except DBError as e:
    204             if this_verbose:

~/Documents/stormdb-python-master/stormdb/access.py in _check_response(self, response, error_str)
    160                     msg = ('StormDB reports error "{0}", not sure what to do '
    161                            'about it.'.format(response))
--> 162                 raise DBError(msg)
    163         elif response.find("<!DOCTYPE html>") == 0:
    164             msg = ('Poorly formed HTTP GET string, this should not happen! '

DBError: 'StormDB reports error "error: You are not allowed to view this project!", not sure what to do about it.'


So


Jamie Lubell
PhD Student, Nemo Lab
Center of Functionally Integrative Neuroscience
Department of Clinical Medicine, Aarhus University
On Nov 17 2019, at 9:23 pm, Chris Bailey <notifications@github.com> wrote:

@Lubell<https://github.com/Lubell> I just realised I may have special powers as a member of the admin group. Could you get the latest git master and test this code:


from stormdb.access import Query
qy = Query('MEG_Headmodel')
qy.get_subjects()

Do you get output?

**Comment by Lubell** [comment]
But.... I just checked with my own project "SFNI" and it worked. Got all my subjects printed carriage return separated.

/

________________________________

**Comment by Lubell** [comment]
Sorry I meant comma and carriage return separated.

/

________________________________
